"""Movement-phase range calculation (requested directly — the movement
phase follows initiative automatically, one pilot at a time, lowest
initiative total first; see turns.py's movement_order/moved_pilot_ids).

Scope confirmed with the user ("set core bien fundamentado" then, later,
"precisión completa" for turning, then "fase de movimiento completa y
fiel a las reglas" for heat + actuator damage): terrain move cost per
tile, extra cost for climbing in elevation, roads at a flat cost, never
ending on an occupied hex, the walk/run/jump distinction (each with its
own to-hit modifier already in app/combat.py's ATTACKER_MOVEMENT_MOD),
turning cost (real Total Warfare rule: 1 MP per hexside turned, out of
the same MP pool as forward movement; moving straight ahead in your
current facing is free), movement generating heat (Heat Scale: Walking
+1, Running +2, Jumping +1 per hex jumped with a minimum of +3 — see
_MOVEMENT_HEAT/execute_move), heat reducing available MP (Heat Scale's
"MP Reduced" column, -1/-2/-3/-4 at 5/10/15/20+ heat, applied to
walking/running/jumping alike — see _heat_mp_penalty), and leg actuator
damage reducing MP (a Hip Actuator hit halves Walking MP and doesn't
stack across both hips; every other destroyed leg actuator is -1 MP
each, cumulative; a leg blown off entirely downs the mech — see
_leg_damage's own doc comment for exactly how each is modeled and
simplified). Modeled as a real state-space search over (position,
facing), not just position — see _reachable_states. Jumping is exempt
from the turning-cost/facing search (RAW: a jumping 'Mech lands facing
whatever direction it likes, for free). Real user request handled
elsewhere, not here: shutdown/restart and ammo-explosion avoidance rolls
from heat now live in turns.py's resolve_heat_phase; standing back up
from prone is psr.py's stand_up (own endpoint, doesn't go through
execute_move); a shut-down or prone mech is rejected outright here (see
MechIncapacitated) rather than just returning 0 MP. Deliberately NOT
modeled here, same "documented simplification" style as the rest of this
codebase: piloting-skill rolls for difficult terrain, stacking limits,
impassable terrain, MASC, backward movement, arm actuator damage
(doesn't affect movement), engine-hit heat doubling (turns.py's own heat-
phase engine-hit handling is a flat +5/hit, not the exact doubling rule).
"""

import heapq
import math
from typing import Literal

from ... import db, units
from ...mapgen import TERRAIN_MOVE_COST
from ...maps import get_map
from . import mechs

MovementType = Literal["walk", "run", "jump"]

# Axial neighbor offsets (redblobgames' standard set) — adjacency doesn't
# depend on pointy/flat-top orientation, only on the axial coordinate
# system itself, which hexToWorld/units.py's _world_delta already use.
_HEX_NEIGHBORS = [(1, 0), (1, -1), (0, -1), (-1, 0), (-1, 1), (0, 1)]
# 8-directional (Chebyshev) — matches squaregrid.py's own distance().
_SQUARE_NEIGHBORS = [(1, 0), (1, 1), (0, 1), (-1, 1), (-1, 0), (-1, -1), (0, -1), (1, -1)]


class UnknownMovementType(ValueError):
    pass


class UnreachableDestination(ValueError):
    pass


class MechIncapacitated(ValueError):
    """A shut-down or prone mech can't move at all — a prone mech's only
    option is psr.stand_up (separate endpoint, costs its own MP there,
    not through this function)."""


# Heat generated by declaring each movement type this round (Heat Scale)
# — jump's own is per-hex-jumped with a floor, computed in execute_move
# once the actual hex count is known, not looked up here.
_MOVEMENT_HEAT = {"walk": 1, "run": 2}

# Heat -> MP-reduction brackets (Heat Scale's "MP Reduced" column),
# checked high to low, applied to walking/running/jumping alike. Was
# missing the 25->5 tier (verified this session directly against the
# rulebook alongside the rest of the Heat Scale — see
# systems/battletech/criticals.py/psr.py's own module docstrings for the
# same verification pass).
_HEAT_MP_PENALTY_BRACKETS = [(25, 5), (20, 4), (15, 3), (10, 2), (5, 1), (0, 0)]


def _heat_mp_penalty(heat: int) -> int:
    for min_heat, penalty in _HEAT_MP_PENALTY_BRACKETS:
        if heat >= min_heat:
            return penalty
    return 0


# Leg critical slots are fixed — Hip is always slot 0, the other three
# leg actuators always follow in this order, both for a hand-built
# mech's default layout (critical_layout.py's _FIXED_TEMPLATE) and for
# any imported MTF (the standard biped layout mandates it).
_HIP_SLOT = 0
_OTHER_LEG_ACTUATOR_SLOTS = {1, 2, 3}  # Upper Leg, Lower Leg, Foot


def _leg_damage(mech: dict) -> tuple[bool, int, bool]:
    """(hip_destroyed, actuator_hits, leg_destroyed) — scans both legs'
    criticals/structure. Total Warfare rule, verified this session: a
    Hip Actuator hit (either leg) halves Walking MP, and a second Hip
    hit in the other leg doesn't stack any further reduction; every
    OTHER destroyed leg actuator (Upper Leg/Lower Leg/Foot, either leg)
    is -1 MP each, cumulative across both legs; a leg blown off entirely
    (structure_current <= 0) fells the mech. This app has no
    prone/stand-up modeling, so a destroyed leg is simplified here to
    "immobile" (0 MP of every type) rather than the real fall+possible
    stand-up-next-turn rules — see module docstring."""
    hip_destroyed = False
    actuator_hits = 0
    leg_destroyed = False
    locations_by_name = {loc["location"]: loc for loc in mech["locations"]}
    for loc_name in ("LL", "RL"):
        loc = locations_by_name.get(loc_name)
        if loc is not None and loc["structure_current"] <= 0:
            leg_destroyed = True
        for crit in mech["criticals"].get(loc_name, []):
            if not crit["hit"]:
                continue
            if crit["slot_index"] == _HIP_SLOT:
                hip_destroyed = True
            elif crit["slot_index"] in _OTHER_LEG_ACTUATOR_SLOTS:
                actuator_hits += 1
    return hip_destroyed, actuator_hits, leg_destroyed


def _budget(mech: dict, movement_type: MovementType) -> int:
    """The real usable MP for this move, after leg-actuator damage and
    the mech's current heat both eat into it — see _leg_damage/
    _heat_mp_penalty's own doc comments for exactly which rules apply."""
    if movement_type not in ("walk", "run", "jump"):
        raise UnknownMovementType(f"Unknown movement_type {movement_type!r}")

    hip_destroyed, actuator_hits, leg_destroyed = _leg_damage(mech)
    if leg_destroyed:
        return 0

    heat_penalty = _heat_mp_penalty(mech["heat_current"])

    if movement_type == "jump":
        return max(0, mech["jump_mp"] - heat_penalty)

    # Applied directly to whichever base MP the movement type actually
    # uses (not run derived from walk*1.5) — this mech's own stored
    # run_mp may already reflect a non-standard multiplier (a
    # MASC/TSM-equipped design, even though this app doesn't model
    # either — see module docstring), so damage/heat scale that same
    # stored value instead of overwriting it with the textbook 1.5x
    # ratio.
    base = mech["walk_mp"] if movement_type == "walk" else mech["run_mp"]
    effective = base // 2 if hip_destroyed else base
    effective = max(0, effective - actuator_hits)
    return max(0, effective - heat_penalty)


def _facing_toward(from_q: int, from_r: int, to_q: int, to_r: int, grid_type: str) -> int:
    """Same convention as units.py's _world_delta/_within_facing_arc (0°
    = world +X, counter-clockwise) — the direction a unit ends up facing
    after moving is just its last step's own direction."""
    if grid_type == "square":
        dx, dz = float(to_q - from_q), float(to_r - from_r)
    else:
        dq, dr = to_q - from_q, to_r - from_r
        dx = math.sqrt(3) * (dq + dr / 2)
        dz = 1.5 * dr
    return round(math.degrees(math.atan2(dz, dx))) % 360


def _facing_degrees(grid_type: str) -> list[int]:
    """Degree value of each neighbor_offsets entry, same index order —
    6 hex facings 60° apart, or 8 square facings 45° apart."""
    offsets = _SQUARE_NEIGHBORS if grid_type == "square" else _HEX_NEIGHBORS
    return [_facing_toward(0, 0, dq, dr, grid_type) for dq, dr in offsets]


def _nearest_facing_index(facing_deg: int, degrees: list[int]) -> int:
    def angular_diff(a: int, b: int) -> int:
        d = abs(a - b) % 360
        return min(d, 360 - d)
    return min(range(len(degrees)), key=lambda i: angular_diff(facing_deg, degrees[i]))


# State = (q, r, facing_index). Real Total Warfare turning rule: moving
# straight ahead in your current facing costs only the destination
# hex's terrain — no separate cost for the "facing change" of having
# arrived there, since you were already facing that way. Turning to
# face a *different* neighbor costs 1 MP per hexside, out of the same
# MP pool, and doesn't move you — so tracing a curved path is turn,
# forward, turn, forward, ... each priced individually. This is why the
# search needs facing as part of its state, not just position.
_State = tuple[int, int, int]


def _reconstruct_path(came_from: dict[_State, _State | None], state: _State) -> list[tuple[int, int]]:
    """Walk the parent-pointer chain back to the origin, keeping only the
    steps that actually changed position (a turn-in-place transition
    revisits the same (q, r), nothing for the frontend to walk through) —
    origin excluded, destination included, in travel order. This is the
    one real route Dijkstra found to this exact (position, facing); a
    different facing at the same hex can legitimately have arrived via a
    different route, which is why paths are reconstructed per-state, not
    cached once per hex."""
    positions: list[tuple[int, int]] = []
    current: _State | None = state
    prev_pos: tuple[int, int] | None = None
    while current is not None:
        pos = (current[0], current[1])
        if pos != prev_pos:
            positions.append(pos)
            prev_pos = pos
        current = came_from.get(current)
    positions.reverse()
    return positions[1:]  # drop the origin


def shortest_terrain_path(
    map_id: int, from_q: int, from_r: int, to_q: int, to_r: int, avoid: set[tuple[int, int]] | None = None,
) -> list[dict] | None:
    """Plain terrain-cost-weighted shortest path between two hexes — no
    MP budget, no turning cost (unlike _reachable_states' real movement-
    phase search, which this deliberately doesn't reuse). Used by a GM's
    free drag reposition (main.py's plain /units/{id}/move) — real user
    request: "cuando el GM hace drag, el movimiento no contara MP, ni
    pasara turno, sin embargo si que tiene que calcular el path mas
    barato y seguirle" — not a real rules-constrained move, but the walk
    should still animate along the actual cheapest terrain route instead
    of a straight line through whatever's in between.

    `avoid` (real user request: "no se puede atravesar un tile ocupado
    por un mech") — hexes the route may never pass THROUGH, typically
    every other unit's current position; the destination itself is
    always allowed to be in `avoid` without effect (whether landing there
    is actually legal is main.py/units.move_unit's own concern, not this
    function's — it only shapes which ROUTE the walk animates along).

    Returns waypoints from just after the origin through the destination
    (origin excluded, same convention _reachable_states' own "path"
    uses) — empty if origin and destination are the same hex (a rotate-
    in-place/no-op reposition), None if the destination is unreachable
    (off the map, cut off by hexes this map has no tile data for, or only
    reachable by crossing an avoided hex) — the caller falls back to a
    straight line in that case."""
    m = get_map(map_id)
    if m is None:
        return None
    grid_type = m["grid_type"]
    tiles = {(t["q"], t["r"]): t for t in m["tiles"]}
    origin, destination = (from_q, from_r), (to_q, to_r)
    if origin not in tiles or destination not in tiles:
        return None
    neighbor_offsets = _SQUARE_NEIGHBORS if grid_type == "square" else _HEX_NEIGHBORS

    best_cost: dict[tuple[int, int], int] = {origin: 0}
    came_from: dict[tuple[int, int], tuple[int, int] | None] = {origin: None}
    frontier: list[tuple[int, tuple[int, int]]] = [(0, origin)]
    while frontier:
        cost, pos = heapq.heappop(frontier)
        if pos == destination:
            break
        if cost > best_cost.get(pos, float("inf")):
            continue
        for dq, dr in neighbor_offsets:
            nxt = (pos[0] + dq, pos[1] + dr)
            if avoid and nxt in avoid and nxt != destination:
                continue
            tile = tiles.get(nxt)
            if tile is None:
                continue
            if tile["terrain"] == "road":
                step_cost = 1
            else:
                elevation_gain = max(0, tile["elevation"] - tiles[pos]["elevation"])
                step_cost = TERRAIN_MOVE_COST.get(tile["terrain"], 1) + elevation_gain
            new_cost = cost + step_cost
            if new_cost < best_cost.get(nxt, float("inf")):
                best_cost[nxt] = new_cost
                came_from[nxt] = pos
                heapq.heappush(frontier, (new_cost, nxt))

    if destination not in came_from:
        return None
    positions: list[tuple[int, int]] = []
    current: tuple[int, int] | None = destination
    while current is not None:
        positions.append(current)
        current = came_from.get(current)
    positions.reverse()
    return [{"q": q, "r": r} for q, r in positions[1:]]


def _reachable_states(unit: dict, mech: dict, movement_type: MovementType) -> dict[_State, dict] | None:
    """{(q, r, facing_idx): {"mp_cost", "hexes", "path"}, ...} — every
    (position, ending facing) combination affordable within budget,
    starting from the unit's own position/facing. "path" is the actual
    sequence of hexes traveled to reach that exact state (see
    _reconstruct_path) — real terrain-following route, not a straight
    line to the destination. None if movement_type is unknown, budget is
    exhausted, or there's no map."""
    budget = _budget(mech, movement_type)
    if budget <= 0:
        return None

    m = get_map(unit["map_id"])
    if m is None:
        return None
    grid_type = m["grid_type"]
    tiles = {(t["q"], t["r"]): t for t in m["tiles"]}
    origin = (unit["q"], unit["r"])

    # Real user request: "no se puede atravesar un tile ocupado por un
    # mech cuando va de un sitio a otro, el pathfinding tiene que tenerlo
    # en cuenta" — ANY other unit's hex blocks passing through, not just
    # an enemy's (this app doesn't model stacking, so two mechs are never
    # allowed to share a hex even mid-route, friend or foe). Landing on
    # one is already blocked separately (reachable_hexes' own `occupied`
    # filter over the final results, and execute_move's destination
    # check) — this is what stops it being crossed along the way too.
    other_units = [u for u in units.list_units(unit["map_id"]) if u["id"] != unit["id"]]
    occupied = {(u["q"], u["r"]) for u in other_units}

    neighbor_offsets = _SQUARE_NEIGHBORS if grid_type == "square" else _HEX_NEIGHBORS
    degrees = _facing_degrees(grid_type)
    n = len(neighbor_offsets)
    start_facing = _nearest_facing_index(unit["facing_deg"], degrees)

    start: _State = (origin[0], origin[1], start_facing)
    best_cost: dict[_State, int] = {start: 0}
    best_hexes: dict[_State, int] = {start: 0}
    came_from: dict[_State, _State | None] = {start: None}
    frontier: list[tuple[int, _State]] = [(0, start)]
    while frontier:
        cost, state = heapq.heappop(frontier)
        if cost > best_cost.get(state, float("inf")):
            continue
        q, r, facing = state
        for nxt_facing in ((facing - 1) % n, (facing + 1) % n):
            nxt: _State = (q, r, nxt_facing)
            new_cost = cost + 1
            if new_cost <= budget and new_cost < best_cost.get(nxt, float("inf")):
                best_cost[nxt] = new_cost
                best_hexes[nxt] = best_hexes[state]
                came_from[nxt] = state
                heapq.heappush(frontier, (new_cost, nxt))
        dq, dr = neighbor_offsets[facing]
        ahead = (q + dq, r + dr)
        tile = tiles.get(ahead)
        if tile is not None and ahead not in occupied:
            if tile["terrain"] == "road":
                step_cost = 1
            else:
                elevation_gain = max(0, tile["elevation"] - tiles[(q, r)]["elevation"])
                step_cost = TERRAIN_MOVE_COST.get(tile["terrain"], 1) + elevation_gain
            new_cost = cost + step_cost
            nxt = (ahead[0], ahead[1], facing)
            if new_cost <= budget and new_cost < best_cost.get(nxt, float("inf")):
                best_cost[nxt] = new_cost
                best_hexes[nxt] = best_hexes[state] + 1
                came_from[nxt] = state
                heapq.heappush(frontier, (new_cost, nxt))

    return {
        state: {
            "mp_cost": best_cost[state],
            "hexes": best_hexes[state],
            "path": _reconstruct_path(came_from, state),
        }
        for state in best_cost
    }


def reachable_hexes(unit_id: int, movement_type: MovementType) -> list[dict] | None:
    """[{"q", "r", "mp_cost", "hexes", "path", "facings"}, ...] this unit
    could move to right now.

    - mp_cost/hexes: the cheapest way to arrive at this hex, via
      whichever ending facing costs least.
    - path: the real hex-by-hex route for that cheapest arrival (see
      _reconstruct_path) — not a straight line to the destination, so
      the frontend can walk a unit through it instead of sliding it
      directly there.
    - facings: every ending facing (degrees) actually affordable at
      this hex within budget — not just the cheapest one. A hex can be
      reachable at all yet only affordable at *some* facings (turning
      further than the leftover MP allows isn't), so the frontend's
      facing picker uses this to grey out/disable the ones that would
      otherwise 422 on execute_move — see the facing picker's own gating.

    None if the unit doesn't exist, [] if it has no mech (nothing to
    move) or zero MP of the requested type."""
    if movement_type not in ("walk", "run", "jump"):
        raise UnknownMovementType(f"Unknown movement_type {movement_type!r}")
    unit = units.get_unit(unit_id)
    if unit is None:
        return None
    if unit["mech_id"] is None:
        return []
    mech = mechs.get_mech(unit["mech_id"])
    if mech is None:
        return []
    budget = _budget(mech, movement_type)
    if budget <= 0:
        return []

    m = get_map(unit["map_id"])
    grid_type = m["grid_type"] if m else "hex"
    origin = (unit["q"], unit["r"])
    other_units = [u for u in units.list_units(unit["map_id"]) if u["id"] != unit_id]
    occupied = {(u["q"], u["r"]) for u in other_units}

    if movement_type == "jump":
        # Jumping ignores terrain cost AND facing entirely (RAW: a
        # jumping 'Mech lands facing whatever direction it likes, for
        # free) — doesn't need a clear path either (it arcs over
        # obstacles) — a flat hex-distance budget. "path" is just the
        # landing hex (no real route to walk through mid-air) and every
        # facing is always affordable (free landing direction), unlike
        # walk/run below.
        tiles = {(t["q"], t["r"]): t for t in (m["tiles"] if m else [])}
        all_facings = _facing_degrees(grid_type)
        results = []
        for (q, r) in tiles:
            if (q, r) == origin or (q, r) in occupied:
                continue
            d = hex_distance(origin, (q, r), grid_type)
            if d <= budget:
                results.append({"q": q, "r": r, "mp_cost": d, "hexes": d, "path": [{"q": q, "r": r}], "facings": all_facings})
        return results

    states = _reachable_states(unit, mech, movement_type)
    if states is None:
        return []
    degrees = _facing_degrees(grid_type)
    best: dict[tuple[int, int], dict] = {}
    facings_by_hex: dict[tuple[int, int], list[int]] = {}
    for (q, r, facing), val in states.items():
        if (q, r) == origin or (q, r) in occupied:
            continue
        facings_by_hex.setdefault((q, r), []).append(degrees[facing])
        cur = best.get((q, r))
        if cur is None or val["mp_cost"] < cur["mp_cost"]:
            best[(q, r)] = val
    return [
        {
            "q": q,
            "r": r,
            "mp_cost": v["mp_cost"],
            "hexes": v["hexes"],
            "path": [{"q": pq, "r": pr} for pq, pr in v["path"]],
            "facings": sorted(facings_by_hex[(q, r)]),
        }
        for (q, r), v in best.items()
    ]


def hex_distance(a: tuple[int, int], b: tuple[int, int], grid_type: str) -> int:
    if grid_type == "square":
        return max(abs(a[0] - b[0]), abs(a[1] - b[1]))
    ax, ay, az = a[0], -a[0] - a[1], a[1]
    bx, by, bz = b[0], -b[0] - b[1], b[1]
    return max(abs(ax - bx), abs(ay - by), abs(az - bz))


def _upsert_round_move(
    conn, campaign_id: int, pilot_id: int, unit_id: int, movement_type: str, hexes_moved: int, mp_spent: int,
) -> None:
    conn.execute(
        """
        INSERT INTO bt_round_moves (campaign_id, pilot_id, unit_id, movement_type, hexes_moved, mp_spent)
        VALUES (?, ?, ?, ?, ?, ?)
        ON CONFLICT(campaign_id, pilot_id) DO UPDATE SET
            unit_id = excluded.unit_id, movement_type = excluded.movement_type,
            hexes_moved = excluded.hexes_moved, mp_spent = excluded.mp_spent,
            created_at = datetime('now')
        """,
        (campaign_id, pilot_id, unit_id, movement_type, hexes_moved, mp_spent),
    )


def record_free_move(campaign_id: int, unit: dict, new_q: int, new_r: int) -> None:
    """A GM free-form reposition (the unrestricted /move endpoint — drag,
    "Mover", or a sidebar drop) during this pilot's movement-phase turn
    still counts as their move for the round — otherwise
    activeMoverPilotId never advances past them and the phase gets stuck
    on that pilot forever whenever the GM doesn't happen to use
    Caminar/Correr/Saltar specifically. hexes_moved is a best-effort
    straight-line hex distance (no MP/terrain accounting, since this
    path bypasses reachable_hexes entirely) — good enough for
    app/combat.py's target_movement_mod(), which only cares about the
    distance. Caller already checked the pilot is part of this round's
    movement_order; a pilotless unit is never part of it to begin with."""
    if unit["pilot_id"] is None:
        return
    m = get_map(unit["map_id"])
    grid_type = m["grid_type"] if m else "hex"
    d = hex_distance((unit["q"], unit["r"]), (new_q, new_r), grid_type)
    with db.connect() as conn:
        _upsert_round_move(conn, campaign_id, unit["pilot_id"], unit["id"], "walk", d, d)


def execute_move(
    campaign_id: int, unit_id: int, q: int, r: int, movement_type: MovementType, facing_deg: int | None = None,
) -> dict:
    """Re-validates the destination server-side (never trusts what the
    frontend highlighted), moves the unit, and records the movement for
    this round — hexes_moved feeds app/combat.py's target_movement_mod()
    automatically once this unit gets attacked, instead of the GM
    guessing it by hand.

    facing_deg is optional — same "pick a direction after the move" UX
    as the free-form move's own FacingPicker; when omitted, whichever
    ending facing was cheapest to reach wins (for a straight walk,
    that's the direction of travel — turning further than that costs
    extra MP, see _reachable_states). Providing an explicit facing_deg
    that costs more than the remaining budget raises
    UnreachableDestination just like an out-of-range hex would — jump
    is the one exception (RAW: free landing facing), so its facing_deg
    is never budget-checked."""
    if movement_type not in ("walk", "run", "jump"):
        raise UnknownMovementType(f"Unknown movement_type {movement_type!r}")
    unit = units.get_unit(unit_id)
    if unit is None or unit["mech_id"] is None:
        raise UnreachableDestination(f"unit {unit_id} has no mech to move")
    mech = mechs.get_mech(unit["mech_id"])
    if mech is None:
        raise UnreachableDestination(f"unit {unit_id} has no mech to move")
    if mech["is_shutdown"] or mech["is_prone"]:
        raise MechIncapacitated(f"unit {unit_id}'s mech is shut down or prone and can't move")
    if mech["destroyed_reason"] is not None:
        raise MechIncapacitated(f"unit {unit_id}'s mech is destroyed and can't move")

    if movement_type == "jump":
        reachable = {(h["q"], h["r"]): h for h in (reachable_hexes(unit_id, movement_type) or [])}
        if (q, r) not in reachable:
            raise UnreachableDestination(f"({q}, {r}) is not reachable via {movement_type!r} for unit {unit_id}")
        if facing_deg is None:
            m = get_map(unit["map_id"])
            grid_type = m["grid_type"] if m else "hex"
            facing_deg = _facing_toward(unit["q"], unit["r"], q, r, grid_type)
        step = reachable[(q, r)]
    else:
        origin = (unit["q"], unit["r"])
        occupied = {(u["q"], u["r"]) for u in units.list_units(unit["map_id"]) if u["id"] != unit_id}
        if (q, r) != origin and (q, r) in occupied:
            raise UnreachableDestination(f"({q}, {r}) is occupied by another unit")
        states = _reachable_states(unit, mech, movement_type)
        candidates = {facing: val for (sq, sr, facing), val in (states or {}).items() if (sq, sr) == (q, r)}
        if not candidates:
            raise UnreachableDestination(f"({q}, {r}) is not reachable via {movement_type!r} for unit {unit_id}")
        m = get_map(unit["map_id"])
        grid_type = m["grid_type"] if m else "hex"
        degrees = _facing_degrees(grid_type)
        if facing_deg is None:
            facing_idx = min(candidates, key=lambda i: candidates[i]["mp_cost"])
        else:
            facing_idx = _nearest_facing_index(facing_deg, degrees)
            if facing_idx not in candidates:
                raise UnreachableDestination(
                    f"not enough MP left to end facing {facing_deg}° at ({q}, {r}) via {movement_type!r}"
                )
        facing_deg = degrees[facing_idx]
        step = candidates[facing_idx]

    updated = units.move_unit(unit_id, q, r, facing_deg)
    # The real hex-by-hex route just taken (walk/run's terrain-following
    # path, or jump's single landing hex — see reachable_hexes/
    # _reachable_states's own "path" doc comments) — real user report:
    # without this, any client that didn't itself pick this destination
    # (the shared table screen watching a move initiated from
    # PlayerView/FirstPersonView, say) had no route data at all and
    # jump's step["path"] (from reachable_hexes, line ~330) is already
    # [{"q", "r"}, ...] dicts, but walk/run's comes straight from
    # _reachable_states/_reconstruct_path as raw (q, r) tuples — normalize
    # both to the same {"q", "r"} shape reachable_hexes() itself already
    # returns (line ~352), matching what the frontend's walkPath consumers
    # (HexMap's UnitMarker) expect. Left un-normalized, a tuple serializes
    # to JSON as a bare [q, r] array, so the frontend's `p.q`/`p.r` reads
    # come back undefined -> NaN, silently poisoning that unit's animation
    # position for the rest of the tab's life (real user report: the unit
    # vanishes on every OTHER connected client until they reload the page —
    # exactly the broadcast-only path Caminar/Correr triggers and drag-and-
    # drop, which never touches walkPath, does not).
    # animated a straight line through whatever was in between instead
    # of the real path. Merged into the same dict already returned here
    # (not a separate return value) so this stays backward-compatible
    # with every existing caller that reads updated["q"]/["facing_deg"].
    updated = {
        **updated,
        "path": [p if isinstance(p, dict) else {"q": p[0], "r": p[1]} for p in step["path"]],
    }

    # Movement itself generates heat (Heat Scale) — walking/running are a
    # flat amount regardless of hexes covered (even a turn-in-place still
    # counts as having Walked/Run); jumping is per-hex-jumped with a
    # floor of 3, since a jump of only 1-2 hexes is exempt from the
    # discount other movement doesn't get.
    heat_gain = max(3, step["hexes"]) if movement_type == "jump" else _MOVEMENT_HEAT[movement_type]
    mechs.add_heat(mech["id"], heat_gain)

    # A pilotless unit (no owner) isn't part of anyone's initiative-based
    # movement_order to begin with — nothing to record it against.
    if unit["pilot_id"] is not None:
        with db.connect() as conn:
            _upsert_round_move(conn, campaign_id, unit["pilot_id"], unit_id, movement_type, step["hexes"], step["mp_cost"])

    return updated
