"""Core combat resolution (ROADMAP.md Fase R2): to-hit, hit location, damage.

Numbers re-verified on 2026-08-15 against official primary sources supplied
by the user: the CAT3500D "BattleTech: A Game of Armored Combat" rulebook
PDF and the Total Warfare quick-reference tables (Attack Modifiers Table,
'Mech Hit Location Table, Heat Point Table). GATOR modifiers (attacker
movement, range, target movement, heat-to-hit) and the front/left/right hit
location tables all match the official tables exactly — including a bug
found and fixed here (`target_movement_mod` was missing the 18-24 -> +5
and 25+ -> +6 tiers). `heat_penalty()`'s breakpoints are confirmed correct;
its OTHER heat effects (movement-point reduction, shutdown-avoidance rolls,
ammo-explosion-avoidance rolls) and heat generated by movement are now
reliably sourced too but deliberately NOT modeled yet — only weapon-fire
heat is tracked. Also still out of scope: called shots, critical-hit rolls,
damage transfer to adjacent locations, physical attacks, the Cluster Hits
Table (SRM/LRM partial-hit resolution — simplified to flat max damage),
minimum-range modifier (needs real hex-distance calc), terrain modifiers
(woods/water/cover), vehicles/aerospace/infantry/ProtoMechs.
"""

import secrets

from . import db, mechs, weapons


class OutOfAmmo(ValueError):
    pass

# ---- GATOR to-hit modifiers ---------------------------------------------

ATTACKER_MOVEMENT_MOD = {"stationary": 0, "walked": 1, "ran": 2, "jumped": 3, "prone": 2}
RANGE_MOD = {"short": 0, "medium": 2, "long": 4}

# heat -> to-hit penalty. See module docstring for the verification caveat.
HEAT_TO_HIT_BRACKETS = [(24, 4), (17, 3), (13, 2), (8, 1), (0, 0)]  # (min_heat, penalty), checked high to low


def heat_penalty(heat: int) -> int:
    for min_heat, penalty in HEAT_TO_HIT_BRACKETS:
        if heat >= min_heat:
            return penalty
    return 0


def target_movement_mod(hexes_moved: int, jumped: bool = False) -> int:
    if hexes_moved <= 2:
        mod = 0
    elif hexes_moved <= 4:
        mod = 1
    elif hexes_moved <= 6:
        mod = 2
    elif hexes_moved <= 9:
        mod = 3
    elif hexes_moved <= 17:
        mod = 4
    elif hexes_moved <= 24:
        mod = 5
    else:
        mod = 6
    return mod + (1 if jumped else 0)


def to_hit_number(
    gunnery: int,
    attacker_movement: str,
    target_hexes_moved: int,
    target_jumped: bool = False,
    range_bracket: str = "short",
    other_modifiers: int = 0,
) -> int:
    return (
        gunnery
        + ATTACKER_MOVEMENT_MOD[attacker_movement]
        + target_movement_mod(target_hexes_moved, target_jumped)
        + RANGE_MOD[range_bracket]
        + other_modifiers
    )


# ---- hit location (2d6) --------------------------------------------------

# roll -> (location, is_critical)
HIT_LOCATION_FRONT_REAR = {
    2: ("CT", True), 3: ("RA", False), 4: ("RA", False), 5: ("RL", False),
    6: ("RT", False), 7: ("CT", False), 8: ("LT", False), 9: ("LL", False),
    10: ("LA", False), 11: ("LA", False), 12: ("HD", False),
}
HIT_LOCATION_LEFT = {
    2: ("LT", True), 3: ("LL", False), 4: ("LA", False), 5: ("LA", False),
    6: ("LL", False), 7: ("LT", False), 8: ("CT", False), 9: ("RT", False),
    10: ("RA", False), 11: ("RL", False), 12: ("HD", False),
}
HIT_LOCATION_RIGHT = {
    2: ("RT", True), 3: ("RL", False), 4: ("RA", False), 5: ("RA", False),
    6: ("RL", False), 7: ("RT", False), 8: ("CT", False), 9: ("LT", False),
    10: ("LA", False), 11: ("LL", False), 12: ("HD", False),
}
HIT_LOCATION_TABLES = {
    "front": HIT_LOCATION_FRONT_REAR,
    "rear": HIT_LOCATION_FRONT_REAR,
    "left": HIT_LOCATION_LEFT,
    "right": HIT_LOCATION_RIGHT,
}


def roll_2d6() -> tuple[int, int, int]:
    d1, d2 = secrets.randbelow(6) + 1, secrets.randbelow(6) + 1
    return d1, d2, d1 + d2


# ---- damage application + undo log --------------------------------------


def _apply_damage(conn, mech_id: int, location: str, rear: bool, amount: int) -> dict:
    row = conn.execute(
        """
        SELECT armor_current, armor_rear_current, structure_current
        FROM mech_locations WHERE mech_id = ? AND location = ?
        """,
        (mech_id, location),
    ).fetchone()
    before = dict(row)

    use_rear = rear and before["armor_rear_current"] is not None
    armor_field = "armor_rear_current" if use_rear else "armor_current"
    armor_before = before[armor_field]

    absorbed = min(amount, armor_before)
    armor_after = armor_before - absorbed
    remaining = amount - absorbed
    structure_after = max(0, before["structure_current"] - remaining)

    conn.execute(
        f"UPDATE mech_locations SET {armor_field} = ?, structure_current = ? "
        "WHERE mech_id = ? AND location = ?",
        (armor_after, structure_after, mech_id, location),
    )

    return {
        "mech_id": mech_id,
        "location": location,
        "armor_field": armor_field,
        "armor_before": armor_before,
        "armor_after": armor_after,
        "structure_before": before["structure_current"],
        "structure_after": structure_after,
        "destroyed": structure_after == 0,
    }


def resolve_attack(
    campaign_id: int,
    target_mech_id: int,
    gunnery: int,
    damage: int | None = None,
    weapon_id: int | None = None,
    attacker_movement: str = "stationary",
    target_hexes_moved: int = 0,
    target_jumped: bool = False,
    range_bracket: str = "short",
    side: str = "front",
    other_modifiers: int = 0,
) -> dict:
    """`damage` (legacy/manual) or `weapon_id` (a mounted mech_weapons row —
    ROADMAP.md Fase R2 follow-up) — the latter looks damage up from
    app/weapons.py's catalog, consumes one shot of ammo if the weapon uses
    any (whether the shot hits or not — firing uses the round either way),
    adds a to-hit penalty from the attacker's CURRENT heat (before this
    shot's own heat is added, since the penalty reflects the heat already
    built up going into the shot), and then adds this weapon's heat to the
    attacker for next time."""
    weapon_name = None
    if weapon_id is not None:
        mech_weapon = mechs.get_mech_weapon(weapon_id)
        if mech_weapon is None:
            raise ValueError(f"Unknown weapon_id {weapon_id!r}")
        if mech_weapon["ammo_remaining"] == 0:
            raise OutOfAmmo(f"Weapon {weapon_id} is out of ammo")
        weapon_name = mech_weapon["weapon_name"]
        stats = weapons.get_weapon(weapon_name)
        damage = stats["damage"]
        mechs.use_ammo(weapon_id)
        attacker_mech = mechs.get_mech(mech_weapon["mech_id"])
        other_modifiers += heat_penalty(attacker_mech["heat_current"])
        mechs.add_heat(mech_weapon["mech_id"], stats["heat"])
    if damage is None:
        raise ValueError("resolve_attack requires either `damage` or `weapon_id`")

    target_number = to_hit_number(
        gunnery, attacker_movement, target_hexes_moved, target_jumped, range_bracket, other_modifiers
    )
    d1, d2, roll = roll_2d6()
    hit = roll >= target_number or roll == 12
    if roll == 2:
        hit = False  # natural 2 always misses

    result = {
        "target_mech_id": target_mech_id,
        "weapon_id": weapon_id,
        "weapon_name": weapon_name,
        "target_number": target_number,
        "roll": roll,
        "roll_dice": [d1, d2],
        "hit": hit,
        "location": None,
        "critical": False,
        "damage": None,
        "mech_destroyed": False,
    }

    if hit:
        loc_d1, loc_d2, loc_roll = roll_2d6()
        location, is_crit = HIT_LOCATION_TABLES[side][loc_roll]
        result["location"] = location
        result["critical"] = is_crit
        result["location_roll"] = loc_roll

        with db.connect() as conn:
            damage_result = _apply_damage(
                conn, target_mech_id, location, rear=(side == "rear"), amount=damage
            )
            result["damage"] = damage_result
            # Official rule: CT or Head internal structure destroyed = whole mech destroyed.
            result["mech_destroyed"] = damage_result["destroyed"] and location in ("CT", "HD")
            _record_action(conn, campaign_id, "attack", {"before": damage_result, "result": result})

    return result


def _record_action(conn, campaign_id: int, action_type: str, payload: dict) -> None:
    import json

    conn.execute(
        "INSERT INTO combat_actions (campaign_id, action_type, payload) VALUES (?, ?, ?)",
        (campaign_id, action_type, json.dumps(payload)),
    )


def undo_last_action(campaign_id: int) -> dict | None:
    import json

    with db.connect() as conn:
        row = conn.execute(
            """
            SELECT id, action_type, payload FROM combat_actions
            WHERE campaign_id = ? AND undone = 0
            ORDER BY id DESC LIMIT 1
            """,
            (campaign_id,),
        ).fetchone()
        if not row:
            return None

        payload = json.loads(row["payload"])
        if row["action_type"] == "attack":
            before = payload["before"]
            conn.execute(
                f"UPDATE mech_locations SET {before['armor_field']} = ?, structure_current = ? "
                "WHERE mech_id = ? AND location = ?",
                (before["armor_before"], before["structure_before"], before["mech_id"], before["location"]),
            )

        conn.execute("UPDATE combat_actions SET undone = 1 WHERE id = ?", (row["id"],))
        return {"action_id": row["id"], "action_type": row["action_type"], "reverted": payload}
